version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: shopzada_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: shopzada_dwh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shopzada_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: shopzada_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shopzada.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - shopzada_net

  metabase:
    image: metabase/metabase
    container_name: shopzada_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - postgres
    networks:
      - shopzada_net

  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: airflow_webserver
    depends_on:
      - airflow-scheduler
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin123@postgres:5432/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - shopzada_net

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow_scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin123@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - shopzada_net

networks:
  shopzada_net:

volumes:
  postgres_data:
  metabase_data:
 
